'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''
<Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(4),  _
 Global.System.Security.Permissions.PermissionSetAttribute(Global.System.Security.Permissions.SecurityAction.Demand, Name:="FullTrust")>  _
Partial Public NotInheritable Class GCA_PL_CONFIGURACOES
    Inherits Microsoft.Office.Tools.Excel.WorksheetBase
    
    Friend WithEvents TB__UNIDADES_CURRICULARES As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TB__TIPOS_DE_UNIDADES_CURRICULARES As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TB__DOCENTES As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TB__SALAS_DE_AULA As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TB__AUTORIZACOES_PARA_LECIONAR As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TB__ATESTADOS As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TB__FERIADOS As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TB__RECESSOS As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TB__DATAS_EVENTUAIS As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TB__PROJETOS_INTEGRADORES As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TB__ESTAGIOS As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TB__HORARIOS As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TB__BLOCOS As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TB__ANDARES As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents RNG__CONFIGURACAO__DADOS_TURMA__ANO As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents RNG__CONFIGURACAO__DADOS_TURMA__AREA_PROFISSIONAL As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents RNG__CONFIGURACAO__DADOS_TURMA__CODIGO_DA_TURMA As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents RNG__CONFIGURACAO__DADOS_TURMA__NOME_CURSO As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents RNG__CONFIGURACAO__DADOS_TURMA__TURNO_LETIVO As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents RNG__CONFIGURACAO__DADOS_TURMA__UNIDADE_EDUCACIONAL As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents RNG__CONFIGURACAO__DADOS_TURMA__VERSAO As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents RNG__CONFIGURACAO__LISTA__DOCENTES As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents RNG__CONFIGURACAO__LISTA__SALAS_DE_AULA As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents RNG__CONFIGURACAO__LISTA__UNIDADES_CURRICULARES As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__ATESTADOS As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__AUTORIZACOES_PARA_LECIONAR As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__DATAS_EVENTUAIS As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__DOCENTES As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__ESTAGIOS As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__FERIADOS As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__HORARIOS As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__PROJETOS_INTEGRADORES As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__RECESSOS As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__SALAS_DE_AULA As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__TIPOS_DE_UNIDADES_CURRICULARES As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__UNIDADES_CURRICULARES As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents RNG__TB__CONFIGURACAO__DADOS_LISTA__DOCENTES As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents RNG__TB__CONFIGURACAO__DADOS_LISTA__SALAS_DE_AULA As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents RNG__TB__CONFIGURACAO__DADOS_LISTA__UNIDADES_CURRICULARES As Microsoft.Office.Tools.Excel.NamedRange
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Public Sub New(ByVal factory As Global.Microsoft.Office.Tools.Excel.Factory, ByVal serviceProvider As Global.System.IServiceProvider)
        MyBase.New(factory, serviceProvider, "GCA_PL_CONFIGURACOES", "GCA_PL_CONFIGURACOES")
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Protected Overrides Sub Initialize()
        MyBase.Initialize
        Globals.GCA_PL_CONFIGURACOES = Me
        Global.System.Windows.Forms.Application.EnableVisualStyles
        Me.InitializeCachedData
        Me.InitializeControls
        Me.InitializeComponents
        Me.InitializeData
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Protected Overrides Sub FinishInitialization()
        Me.OnStartup
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Protected Overrides Sub InitializeDataBindings()
        Me.BeginInitialization
        Me.BindToData
        Me.EndInitialization
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub InitializeCachedData()
        If (Me.DataHost Is Nothing) Then
            Return
        End If
        If Me.DataHost.IsCacheInitialized Then
            Me.DataHost.FillCachedData(Me)
        End If
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub InitializeData()
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub BindToData()
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Private Sub StartCaching(ByVal MemberName As String)
        Me.DataHost.StartCaching(Me, MemberName)
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Private Sub StopCaching(ByVal MemberName As String)
        Me.DataHost.StopCaching(Me, MemberName)
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Private Function IsCached(ByVal MemberName As String) As Boolean
        Return Me.DataHost.IsCached(Me, MemberName)
    End Function
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub BeginInitialization()
        Me.BeginInit
        Me.TB__UNIDADES_CURRICULARES.BeginInit
        Me.TB__TIPOS_DE_UNIDADES_CURRICULARES.BeginInit
        Me.TB__DOCENTES.BeginInit
        Me.TB__SALAS_DE_AULA.BeginInit
        Me.TB__AUTORIZACOES_PARA_LECIONAR.BeginInit
        Me.TB__ATESTADOS.BeginInit
        Me.TB__FERIADOS.BeginInit
        Me.TB__RECESSOS.BeginInit
        Me.TB__DATAS_EVENTUAIS.BeginInit
        Me.TB__PROJETOS_INTEGRADORES.BeginInit
        Me.TB__ESTAGIOS.BeginInit
        Me.TB__HORARIOS.BeginInit
        Me.TB__BLOCOS.BeginInit
        Me.TB__ANDARES.BeginInit
        Me.RNG__CONFIGURACAO__DADOS_TURMA__ANO.BeginInit
        Me.RNG__CONFIGURACAO__DADOS_TURMA__AREA_PROFISSIONAL.BeginInit
        Me.RNG__CONFIGURACAO__DADOS_TURMA__CODIGO_DA_TURMA.BeginInit
        Me.RNG__CONFIGURACAO__DADOS_TURMA__NOME_CURSO.BeginInit
        Me.RNG__CONFIGURACAO__DADOS_TURMA__TURNO_LETIVO.BeginInit
        Me.RNG__CONFIGURACAO__DADOS_TURMA__UNIDADE_EDUCACIONAL.BeginInit
        Me.RNG__CONFIGURACAO__DADOS_TURMA__VERSAO.BeginInit
        Me.RNG__CONFIGURACAO__LISTA__DOCENTES.BeginInit
        Me.RNG__CONFIGURACAO__LISTA__SALAS_DE_AULA.BeginInit
        Me.RNG__CONFIGURACAO__LISTA__UNIDADES_CURRICULARES.BeginInit
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__ATESTADOS.BeginInit
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__AUTORIZACOES_PARA_LECIONAR.BeginInit
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__DATAS_EVENTUAIS.BeginInit
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__DOCENTES.BeginInit
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__ESTAGIOS.BeginInit
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__FERIADOS.BeginInit
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__HORARIOS.BeginInit
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__PROJETOS_INTEGRADORES.BeginInit
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__RECESSOS.BeginInit
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__SALAS_DE_AULA.BeginInit
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__TIPOS_DE_UNIDADES_CURRICULARES.BeginInit
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__UNIDADES_CURRICULARES.BeginInit
        Me.RNG__TB__CONFIGURACAO__DADOS_LISTA__DOCENTES.BeginInit
        Me.RNG__TB__CONFIGURACAO__DADOS_LISTA__SALAS_DE_AULA.BeginInit
        Me.RNG__TB__CONFIGURACAO__DADOS_LISTA__UNIDADES_CURRICULARES.BeginInit
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub EndInitialization()
        Me.RNG__TB__CONFIGURACAO__DADOS_LISTA__UNIDADES_CURRICULARES.EndInit
        Me.RNG__TB__CONFIGURACAO__DADOS_LISTA__SALAS_DE_AULA.EndInit
        Me.RNG__TB__CONFIGURACAO__DADOS_LISTA__DOCENTES.EndInit
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__UNIDADES_CURRICULARES.EndInit
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__TIPOS_DE_UNIDADES_CURRICULARES.EndInit
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__SALAS_DE_AULA.EndInit
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__RECESSOS.EndInit
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__PROJETOS_INTEGRADORES.EndInit
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__HORARIOS.EndInit
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__FERIADOS.EndInit
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__ESTAGIOS.EndInit
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__DOCENTES.EndInit
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__DATAS_EVENTUAIS.EndInit
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__AUTORIZACOES_PARA_LECIONAR.EndInit
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__ATESTADOS.EndInit
        Me.RNG__CONFIGURACAO__LISTA__UNIDADES_CURRICULARES.EndInit
        Me.RNG__CONFIGURACAO__LISTA__SALAS_DE_AULA.EndInit
        Me.RNG__CONFIGURACAO__LISTA__DOCENTES.EndInit
        Me.RNG__CONFIGURACAO__DADOS_TURMA__VERSAO.EndInit
        Me.RNG__CONFIGURACAO__DADOS_TURMA__UNIDADE_EDUCACIONAL.EndInit
        Me.RNG__CONFIGURACAO__DADOS_TURMA__TURNO_LETIVO.EndInit
        Me.RNG__CONFIGURACAO__DADOS_TURMA__NOME_CURSO.EndInit
        Me.RNG__CONFIGURACAO__DADOS_TURMA__CODIGO_DA_TURMA.EndInit
        Me.RNG__CONFIGURACAO__DADOS_TURMA__AREA_PROFISSIONAL.EndInit
        Me.RNG__CONFIGURACAO__DADOS_TURMA__ANO.EndInit
        Me.TB__ANDARES.EndInit
        Me.TB__BLOCOS.EndInit
        Me.TB__HORARIOS.EndInit
        Me.TB__ESTAGIOS.EndInit
        Me.TB__PROJETOS_INTEGRADORES.EndInit
        Me.TB__DATAS_EVENTUAIS.EndInit
        Me.TB__RECESSOS.EndInit
        Me.TB__FERIADOS.EndInit
        Me.TB__ATESTADOS.EndInit
        Me.TB__AUTORIZACOES_PARA_LECIONAR.EndInit
        Me.TB__SALAS_DE_AULA.EndInit
        Me.TB__DOCENTES.EndInit
        Me.TB__TIPOS_DE_UNIDADES_CURRICULARES.EndInit
        Me.TB__UNIDADES_CURRICULARES.EndInit
        Me.EndInit
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub InitializeControls()
        Me.TB__UNIDADES_CURRICULARES = Globals.Factory.CreateListObject(Nothing, Nothing, "GCA_PL_CONFIGURACOES:TB__UNIDADES_CURRICULARES", "TB__UNIDADES_CURRICULARES", Me)
        Me.TB__TIPOS_DE_UNIDADES_CURRICULARES = Globals.Factory.CreateListObject(Nothing, Nothing, "GCA_PL_CONFIGURACOES:TB__TIPOS_DE_UNIDADES_CURRICULARES", "TB__TIPOS_DE_UNIDADES_CURRICULARES", Me)
        Me.TB__DOCENTES = Globals.Factory.CreateListObject(Nothing, Nothing, "GCA_PL_CONFIGURACOES:TB__DOCENTES", "TB__DOCENTES", Me)
        Me.TB__SALAS_DE_AULA = Globals.Factory.CreateListObject(Nothing, Nothing, "GCA_PL_CONFIGURACOES:TB__SALAS_DE_AULA", "TB__SALAS_DE_AULA", Me)
        Me.TB__AUTORIZACOES_PARA_LECIONAR = Globals.Factory.CreateListObject(Nothing, Nothing, "GCA_PL_CONFIGURACOES:TB__AUTORIZACOES_PARA_LECIONAR", "TB__AUTORIZACOES_PARA_LECIONAR", Me)
        Me.TB__ATESTADOS = Globals.Factory.CreateListObject(Nothing, Nothing, "GCA_PL_CONFIGURACOES:TB__ATESTADOS", "TB__ATESTADOS", Me)
        Me.TB__FERIADOS = Globals.Factory.CreateListObject(Nothing, Nothing, "GCA_PL_CONFIGURACOES:TB__FERIADOS", "TB__FERIADOS", Me)
        Me.TB__RECESSOS = Globals.Factory.CreateListObject(Nothing, Nothing, "GCA_PL_CONFIGURACOES:TB__RECESSOS", "TB__RECESSOS", Me)
        Me.TB__DATAS_EVENTUAIS = Globals.Factory.CreateListObject(Nothing, Nothing, "GCA_PL_CONFIGURACOES:TB__DATAS_EVENTUAIS", "TB__DATAS_EVENTUAIS", Me)
        Me.TB__PROJETOS_INTEGRADORES = Globals.Factory.CreateListObject(Nothing, Nothing, "GCA_PL_CONFIGURACOES:TB__PROJETOS_INTEGRADORES", "TB__PROJETOS_INTEGRADORES", Me)
        Me.TB__ESTAGIOS = Globals.Factory.CreateListObject(Nothing, Nothing, "GCA_PL_CONFIGURACOES:TB__ESTAGIOS", "TB__ESTAGIOS", Me)
        Me.TB__HORARIOS = Globals.Factory.CreateListObject(Nothing, Nothing, "GCA_PL_CONFIGURACOES:TB__HORARIOS", "TB__HORARIOS", Me)
        Me.TB__BLOCOS = Globals.Factory.CreateListObject(Nothing, Nothing, "GCA_PL_CONFIGURACOES:TB__BLOCOS", "TB__BLOCOS", Me)
        Me.TB__ANDARES = Globals.Factory.CreateListObject(Nothing, Nothing, "GCA_PL_CONFIGURACOES:TB__ANDARES", "TB__ANDARES", Me)
        Me.RNG__CONFIGURACAO__DADOS_TURMA__ANO = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RNG__CONFIGURACAO__DADOS_TURMA__ANO", "RNG__CONFIGURACAO__DADOS_TURMA__ANO", Me)
        Me.RNG__CONFIGURACAO__DADOS_TURMA__AREA_PROFISSIONAL = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RNG__CONFIGURACAO__DADOS_TURMA__AREA_PROFISSIONAL", "RNG__CONFIGURACAO__DADOS_TURMA__AREA_PROFISSIONAL", Me)
        Me.RNG__CONFIGURACAO__DADOS_TURMA__CODIGO_DA_TURMA = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RNG__CONFIGURACAO__DADOS_TURMA__CODIGO_DA_TURMA", "RNG__CONFIGURACAO__DADOS_TURMA__CODIGO_DA_TURMA", Me)
        Me.RNG__CONFIGURACAO__DADOS_TURMA__NOME_CURSO = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RNG__CONFIGURACAO__DADOS_TURMA__NOME_CURSO", "RNG__CONFIGURACAO__DADOS_TURMA__NOME_CURSO", Me)
        Me.RNG__CONFIGURACAO__DADOS_TURMA__TURNO_LETIVO = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RNG__CONFIGURACAO__DADOS_TURMA__TURNO_LETIVO", "RNG__CONFIGURACAO__DADOS_TURMA__TURNO_LETIVO", Me)
        Me.RNG__CONFIGURACAO__DADOS_TURMA__UNIDADE_EDUCACIONAL = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RNG__CONFIGURACAO__DADOS_TURMA__UNIDADE_EDUCACIONAL", "RNG__CONFIGURACAO__DADOS_TURMA__UNIDADE_EDUCACIONAL", Me)
        Me.RNG__CONFIGURACAO__DADOS_TURMA__VERSAO = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RNG__CONFIGURACAO__DADOS_TURMA__VERSAO", "RNG__CONFIGURACAO__DADOS_TURMA__VERSAO", Me)
        Me.RNG__CONFIGURACAO__LISTA__DOCENTES = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RNG__CONFIGURACAO__LISTA__DOCENTES", "RNG__CONFIGURACAO__LISTA__DOCENTES", Me)
        Me.RNG__CONFIGURACAO__LISTA__SALAS_DE_AULA = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RNG__CONFIGURACAO__LISTA__SALAS_DE_AULA", "RNG__CONFIGURACAO__LISTA__SALAS_DE_AULA", Me)
        Me.RNG__CONFIGURACAO__LISTA__UNIDADES_CURRICULARES = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RNG__CONFIGURACAO__LISTA__UNIDADES_CURRICULARES", "RNG__CONFIGURACAO__LISTA__UNIDADES_CURRICULARES", Me)
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__ATESTADOS = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__ATESTADOS", "RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__ATESTADOS", Me)
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__AUTORIZACOES_PARA_LECIONAR = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__AUTORIZACOES_PARA_LECIONAR", "RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__AUTORIZACOES_PARA_LECIONAR", Me)
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__DATAS_EVENTUAIS = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__DATAS_EVENTUAIS", "RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__DATAS_EVENTUAIS", Me)
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__DOCENTES = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__DOCENTES", "RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__DOCENTES", Me)
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__ESTAGIOS = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__ESTAGIOS", "RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__ESTAGIOS", Me)
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__FERIADOS = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__FERIADOS", "RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__FERIADOS", Me)
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__HORARIOS = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__HORARIOS", "RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__HORARIOS", Me)
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__PROJETOS_INTEGRADORES = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__PROJETOS_INTEGRADORES", "RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__PROJETOS_INTEGRADORES", Me)
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__RECESSOS = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__RECESSOS", "RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__RECESSOS", Me)
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__SALAS_DE_AULA = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__SALAS_DE_AULA", "RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__SALAS_DE_AULA", Me)
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__TIPOS_DE_UNIDADES_CURRICULARES = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__TIPOS_DE_UNIDADES_CURRICULARES", "RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__TIPOS_DE_UNIDADES_CURRICULARES", Me)
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__UNIDADES_CURRICULARES = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__UNIDADES_CURRICULARES", "RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__UNIDADES_CURRICULARES", Me)
        Me.RNG__TB__CONFIGURACAO__DADOS_LISTA__DOCENTES = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RNG__TB__CONFIGURACAO__DADOS_LISTA__DOCENTES", "RNG__TB__CONFIGURACAO__DADOS_LISTA__DOCENTES", Me)
        Me.RNG__TB__CONFIGURACAO__DADOS_LISTA__SALAS_DE_AULA = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RNG__TB__CONFIGURACAO__DADOS_LISTA__SALAS_DE_AULA", "RNG__TB__CONFIGURACAO__DADOS_LISTA__SALAS_DE_AULA", Me)
        Me.RNG__TB__CONFIGURACAO__DADOS_LISTA__UNIDADES_CURRICULARES = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RNG__TB__CONFIGURACAO__DADOS_LISTA__UNIDADES_CURRICULARES", "RNG__TB__CONFIGURACAO__DADOS_LISTA__UNIDADES_CURRICULARES", Me)
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub InitializeComponents()
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Private Function NeedsFill(ByVal MemberName As String) As Boolean
        Return Me.DataHost.NeedsFill(Me, MemberName)
    End Function
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Protected Overrides Sub OnShutdown()
        Me.RNG__TB__CONFIGURACAO__DADOS_LISTA__UNIDADES_CURRICULARES.Dispose
        Me.RNG__TB__CONFIGURACAO__DADOS_LISTA__SALAS_DE_AULA.Dispose
        Me.RNG__TB__CONFIGURACAO__DADOS_LISTA__DOCENTES.Dispose
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__UNIDADES_CURRICULARES.Dispose
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__TIPOS_DE_UNIDADES_CURRICULARES.Dispose
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__SALAS_DE_AULA.Dispose
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__RECESSOS.Dispose
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__PROJETOS_INTEGRADORES.Dispose
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__HORARIOS.Dispose
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__FERIADOS.Dispose
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__ESTAGIOS.Dispose
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__DOCENTES.Dispose
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__DATAS_EVENTUAIS.Dispose
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__AUTORIZACOES_PARA_LECIONAR.Dispose
        Me.RNG__CONFIGURACAO__QUANTIDADES_REGISTROS__ATESTADOS.Dispose
        Me.RNG__CONFIGURACAO__LISTA__UNIDADES_CURRICULARES.Dispose
        Me.RNG__CONFIGURACAO__LISTA__SALAS_DE_AULA.Dispose
        Me.RNG__CONFIGURACAO__LISTA__DOCENTES.Dispose
        Me.RNG__CONFIGURACAO__DADOS_TURMA__VERSAO.Dispose
        Me.RNG__CONFIGURACAO__DADOS_TURMA__UNIDADE_EDUCACIONAL.Dispose
        Me.RNG__CONFIGURACAO__DADOS_TURMA__TURNO_LETIVO.Dispose
        Me.RNG__CONFIGURACAO__DADOS_TURMA__NOME_CURSO.Dispose
        Me.RNG__CONFIGURACAO__DADOS_TURMA__CODIGO_DA_TURMA.Dispose
        Me.RNG__CONFIGURACAO__DADOS_TURMA__AREA_PROFISSIONAL.Dispose
        Me.RNG__CONFIGURACAO__DADOS_TURMA__ANO.Dispose
        Me.TB__ANDARES.Dispose
        Me.TB__BLOCOS.Dispose
        Me.TB__HORARIOS.Dispose
        Me.TB__ESTAGIOS.Dispose
        Me.TB__PROJETOS_INTEGRADORES.Dispose
        Me.TB__DATAS_EVENTUAIS.Dispose
        Me.TB__RECESSOS.Dispose
        Me.TB__FERIADOS.Dispose
        Me.TB__ATESTADOS.Dispose
        Me.TB__AUTORIZACOES_PARA_LECIONAR.Dispose
        Me.TB__SALAS_DE_AULA.Dispose
        Me.TB__DOCENTES.Dispose
        Me.TB__TIPOS_DE_UNIDADES_CURRICULARES.Dispose
        Me.TB__UNIDADES_CURRICULARES.Dispose
        MyBase.OnShutdown
    End Sub
End Class

Partial Friend NotInheritable Class Globals
    
    Private Shared _GCA_PL_CONFIGURACOES As GCA_PL_CONFIGURACOES
    
    Friend Shared Property GCA_PL_CONFIGURACOES() As GCA_PL_CONFIGURACOES
        Get
            Return _GCA_PL_CONFIGURACOES
        End Get
        Set
            If (_GCA_PL_CONFIGURACOES Is Nothing) Then
                _GCA_PL_CONFIGURACOES = value
            Else
                Throw New System.NotSupportedException()
            End If
        End Set
    End Property
End Class
