'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    'através de uma ferramenta como ResGen ou Visual Studio.
    'Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    'com a opção /str, ou recrie o projeto do VS.
    '''<summary>
    '''  Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GCA___Turma_000._0000._0000.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Substitui a propriedade CurrentUICulture do thread atual para todas as
        '''  pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_ConfiguracoesAcadêmicas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_ConfiguracoesAcadêmicas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_ConfiguracoesAdministrativas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_ConfiguracoesAdministrativas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_ConfiguracoesDeEventos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_ConfiguracoesDeEventos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_ConfiguracoesdeInfraestrutura() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_ConfiguracoesdeInfraestrutura", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_ConfiguracoesEducacionais() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_ConfiguracoesEducacionais", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_ConfigurarAndares() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_ConfigurarAndares", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_ConfigurarAreaProfissional() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_ConfigurarAreaProfissional", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_ConfigurarAtestados() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_ConfigurarAtestados", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_ConfigurarAutorizacoesParaLecionar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_ConfigurarAutorizacoesParaLecionar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_ConfigurarBlocos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_ConfigurarBlocos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_ConfigurarCodigoDaTurma() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_ConfigurarCodigoDaTurma", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_ConfigurarDatasEventuais() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_ConfigurarDatasEventuais", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_ConfigurarDocentes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_ConfigurarDocentes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_ConfigurarFeriados() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_ConfigurarFeriados", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_ConfigurarHorarisDeAulas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_ConfigurarHorarisDeAulas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_ConfigurarNomeDoCurso() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_ConfigurarNomeDoCurso", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_ConfigurarRecessos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_ConfigurarRecessos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_ConfigurarSalasDeAula() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_ConfigurarSalasDeAula", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_ConfigurarTiposDeUnidadesCurriculares() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_ConfigurarTiposDeUnidadesCurriculares", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_ConfigurarTurnoLetivo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_ConfigurarTurnoLetivo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_ConfigurarUnidadeEducacional() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_ConfigurarUnidadeEducacional", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_ConfigurarUnidadesCurriculares() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_ConfigurarUnidadesCurriculares", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_CriarCronogramaComIA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_CriarCronogramaComIA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_EditarCronogramaComIA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_EditarCronogramaComIA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_EditarCronogramaManualmente() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_EditarCronogramaManualmente", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_ExportarEmPDF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_ExportarEmPDF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_ExportarEmXLSX() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_ExportarEmXLSX", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_FinalizarSessao() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_FinalizarSessao", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_IconePadrao() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_IconePadrao", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_IniciarSessao() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_IniciarSessao", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_IrParaEditarCronograma() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_IrParaEditarCronograma", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_VisualizarCalendarioAcademico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_VisualizarCalendarioAcademico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_VisualizarErros() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_VisualizarErros", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icn_VoltarParaMenuInicial() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icn_VoltarParaMenuInicial", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
